/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DegenGold__factory } from "./DegenGold__factory";
export { DegenScrap__factory } from "./DegenScrap__factory";
export { DegenShrooms__factory } from "./DegenShrooms__factory";
