/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DegenGold } from "./DegenGold";
export type { DegenScrap } from "./DegenScrap";
export type { DegenShrooms } from "./DegenShrooms";
