/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DownBadDoomers } from "./DownBadDoomers";
export type { SmolDoomers } from "./SmolDoomers";
export type { SmolrDoomers } from "./SmolrDoomers";
