/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface DystopianDataFactoryInterface extends utils.Interface {
  functions: {
    "deployDystopianData(uint256,string,uint256,address,address,address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "deployDystopianData"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployDystopianData",
    values: [BigNumberish, string, BigNumberish, string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployDystopianData",
    data: BytesLike
  ): Result;

  events: {
    "DystopianDataDeployed(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DystopianDataDeployed"): EventFragment;
}

export interface DystopianDataDeployedEventObject {
  dataContract: string;
}
export type DystopianDataDeployedEvent = TypedEvent<
  [string],
  DystopianDataDeployedEventObject
>;

export type DystopianDataDeployedEventFilter =
  TypedEventFilter<DystopianDataDeployedEvent>;

export interface DystopianDataFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DystopianDataFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployDystopianData(
      _id: BigNumberish,
      _name: string,
      _renameCost: BigNumberish,
      _worlds: string,
      _dystopians: string,
      _payments: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  deployDystopianData(
    _id: BigNumberish,
    _name: string,
    _renameCost: BigNumberish,
    _worlds: string,
    _dystopians: string,
    _payments: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployDystopianData(
      _id: BigNumberish,
      _name: string,
      _renameCost: BigNumberish,
      _worlds: string,
      _dystopians: string,
      _payments: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "DystopianDataDeployed(address)"(
      dataContract?: null
    ): DystopianDataDeployedEventFilter;
    DystopianDataDeployed(
      dataContract?: null
    ): DystopianDataDeployedEventFilter;
  };

  estimateGas: {
    deployDystopianData(
      _id: BigNumberish,
      _name: string,
      _renameCost: BigNumberish,
      _worlds: string,
      _dystopians: string,
      _payments: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployDystopianData(
      _id: BigNumberish,
      _name: string,
      _renameCost: BigNumberish,
      _worlds: string,
      _dystopians: string,
      _payments: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
