/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DegenData } from "./DegenData";
export type { DegenDataFactory } from "./DegenDataFactory";
export type { DystopianData } from "./DystopianData";
export type { DystopianDataFactory } from "./DystopianDataFactory";
export type { StakingRewards } from "./StakingRewards";
export type { WorldTreasury } from "./WorldTreasury";
