import Classes from './src/home-features.module.scss'
import Container from '@/components/container'
import Title from '@/components/title'
import ListMenu from '@/components/list-menu'

/**
 * Interfaces
 */
interface Props {
    //
}

/**
 * Features component
 */
const HomeFeatures = ({}: Props) => {
    return (
        <Container>
            <div className={Classes.wrapper}>
                <div className={Classes.root}>
                    <div className={Classes.section}>
                        <div className={Classes.image}>
                            <div className={Classes.doomers} />
                        </div>

                        <div className={Classes.content}>
                            <ListMenu
                                font="pixel"
                                buttons={[
                                    {
                                        /*
                                    my portfolio is down, 
but i am proud of
 . 

                                    */
                                        name: 'my portfolio is down',
                                    },
                                    {
                                        name: 'but i am proud of',
                                    },
                                    {
                                        name: 'my nft collection',
                                        href: 'https://campfire.exchange/collections/0xf2b7638db11427821b03def718d58a0b4c93404c',
                                    },
                                ]}
                            />
                        </div>
                    </div>

                    <div className={Classes.section}>
                        <div className={Classes.content}>
                            <div>
                                <h2>
                                    Explore an <span className="text-primary">Open World</span>
                                </h2>
                                <p>
                                    Meet other players, harvest resources, craft equipment, forage
                                    for collectables, battle in open-world PVP
                                </p>
                            </div>

                            <div>
                                <h2>
                                    <span className="text-primary">Level-Up</span> your NFTs
                                </h2>
                                <p>
                                    Degens, the playable characters of Degen Dystopia are NFTs that
                                    can be leveled up by playing the game.
                                </p>
                            </div>
                        </div>

                        <div className={Classes.image}>
                            <div className={Classes.world} />
                        </div>
                    </div>

                    <div className={Classes.section}>
                        <div className={Classes.image}>
                            <img src="/images/gold.png" className={Classes.coins} alt="coins" />
                            <img src="/images/scrap.png" className={Classes.coins} alt="coins" />
                        </div>

                        <div className={Classes.content}>
                            <div>
                                <h2>
                                    <span className="text-primary">Win</span> to Earn
                                </h2>
                                <p>
                                    Degen Dystopia features a non-inflationary revenue sharing model
                                    which allows players to comete for yields generated by the game.
                                </p>
                            </div>
                        </div>
                    </div>

                    <div className={Classes.section}>
                        <div className={Classes.content}>
                            <div>
                                <h2>
                                    Crafting <span className="text-primary">DYSTOPIANs</span>
                                </h2>
                                <p>Craft NFT minions and command them in battle.</p>
                            </div>
                        </div>

                        <div className={Classes.image}>
                            <img src="/images/dystopian.gif" className={Classes.dao} alt="coins" />
                            <img
                                src="/images/dystopian-2.gif"
                                className={Classes.dao}
                                alt="coins"
                            />
                        </div>
                    </div>

                    <div className={Classes.section}>
                        <div className={Classes.image}>
                            <img src="/images/scroll.png" className={Classes.dao} alt="coins" />
                        </div>

                        <div className={Classes.content}>
                            <div>
                                <h2>
                                    Open Governance <span className="text-primary">DAO</span>
                                </h2>
                                <p>
                                    Degen Dystopia is designed to be governed via DAO mechanics.
                                    Unlike other games, the players will choose the way the game
                                    evolves, both from within the game, as well as by the ability to
                                    propose and vote on changes to Degen Dystopia itself.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </Container>
    )
}

// Export component
export default HomeFeatures
